import os

from dotenv import load_dotenv
import psycopg2

load_dotenv()

table_name = "api_keys"
drop_table = f"""DROP TABLE IF EXISTS {table_name};"""

create_table = f"""
    CREATE TABLE IF NOT EXISTS {table_name} (
        api_key_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
        created TIMESTAMPTZ DEFAULT timezone('utc', NOW()) NOT NULL,
        user_id UUID UNIQUE NOT NULL,
        key TEXT NOT NULL,
        name TEXT NOT NULL,
        description TEXT NOT NULL,
        plan TEXT NOT NULL,
        is_active BOOLEAN DEFAULT TRUE NOT NULL
    );
"""

indexes = [
    f"CREATE INDEX IF NOT EXISTS {table_name}_key_idx ON {table_name} (key);",
]

host = os.environ.get("DATABASE_HOST")
db = os.environ.get("DATABASE_NAME")
user = os.environ.get("DATABASE_USER")
password = os.environ.get("DATABASE_PASSWORD")

try:
    connection = psycopg2.connect(
        host=host,
        database=db,
        user=user,
        password=password,
    )

    cursor = connection.cursor()

    cursor.execute(drop_table)
    cursor.execute(create_table)
    for index in indexes:
        cursor.execute(index)
    connection.commit()
    print("Table created successfully.")
except Exception as error:
    connection.rollback()
    print("Error while connecting to PostgreSQL", error)
    print("Table creation failed.")
finally:
    cursor.close()
    connection.close()
